name: Release

on:
  push:
    branches:
      - dev_automate
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get last commit message
      run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

    - name: Zip the folder
      run: |
        zip -r "${{ env.COMMIT_MESSAGE }}.zip" Chinese\ for\ learners\ language\ pack/

    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: "Release ${{ github.ref }}"
        workdir: "Chinese for learners language pack"
