name: Release

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release name'
        required: true
      tag_name:
        description: 'Tag name'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Zip the folder
      run: |
        zip -r "Chinese.For.Learners.zip" Chinese\ for\ learners\ language\ pack/

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: "Chinese.For.Learners.zip"
        name: ${{ inputs.release_name }}
        token: ${{ inputs.tag_name }}
