name: Translate and commit

on:
  workflow_dispatch:
    inputs:
      minecraft_version:
        description: 'Minecraft Version'
        required: false

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore src/MinecraftTranslator/MinecraftTranslator/MinecraftTranslator.fsproj

    - name: Build
      run: dotnet build --no-restore src/MinecraftTranslator/MinecraftTranslator/MinecraftTranslator.fsproj

    - name: Get minecraft version
      run: |
        if [ -z "${{ inputs.minecraft_version }}" ]; then
          VERSION=$(dotnet run --no-build --project src/MinecraftTranslator/MinecraftTranslator/MinecraftTranslator.fsproj list-versions --latest-only)
        else
          VERSION=${{ inputs.minecraft_version }}
        fi
        echo "minecraft_version=$VERSION" >> $GITHUB_ENV


    - name: Translate to zh_ln
      run: dotnet run --no-build --project src/MinecraftTranslator/MinecraftTranslator/MinecraftTranslator.fsproj translate --language zh_ln --version ${{env.minecraft_version}}
      env:
        AZURE_TRANSLATOR_KEY: ${{ secrets.AZURE_TRANSLATOR_KEY }}

    - name: Translate to zh_py
      run: dotnet run --no-build --project src/MinecraftTranslator/MinecraftTranslator/MinecraftTranslator.fsproj translate --language zh_py --version ${{env.minecraft_version}}
      env:
        AZURE_TRANSLATOR_KEY: ${{ secrets.AZURE_TRANSLATOR_KEY }}

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        file_pattern: '*.json'
        branch: v${{env.minecraft_version}}
        create_branch: true
        commit_message: Version ${{env.minecraft_version}}
